apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: REPLACE_REPOSITORY
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: REPLACE_NAMESPACE
