---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: s2i-nodejs
  namespace: openshift
  labels:
    pipeline.openshift.io/runtime: nodejs
  annotations:
    operator.tekton.dev/preserve-namespace: "true"
spec:
  params:
    - name: APP_NAME
      type: string
  resources:
    - name: app-source
      type: git
    - name: app-image
      type: image

  tasks:
    - name: build
      taskRef:
        name: s2i-nodejs
        kind: ClusterTask
      resources:
        inputs:
          - name: source
            resource: app-source
        outputs:
          - name: image
            resource: app-image
      params:
        - name: TLSVERIFY
          value: "false"

    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build
      params:
        - name: ARGS
          value: ["rollout", "latest", "$(params.APP_NAME)"]
